"""exp15: the smallest real ONNX -> native C++ compiler. Targets exactly the
architecture class exp1/exp9 already hand-validated (Gemm -> Relu -> Gemm ->
Softmax, i.e. Linear -> ReLU -> Linear -> Softmax) — three op types, no
fusion, no graph optimization, no dynamic shapes, no control flow. This
experiment asks "can we auto-generate correct native code at all", not "can
we compile arbitrary models" or "is the generated code fast" — those are
separate, later questions (see research/experiments/exp15's results.md).

Codegen emits CALLS to common.hpp's existing, already-validated ops
(linear/relu_inplace/softmax_rows) — it never generates a numerical kernel
itself. Output artifact layout matches mlp_model.hpp's existing convention
exactly (shapes.txt, fc1_weight.bin, ...), so python/compare.py and the
sajal CLI work UNCHANGED on compiler-generated models — no special-casing
anywhere in the existing toolchain.
"""
import pathlib
import shutil
import subprocess
import sys

import numpy as np
import onnx
from onnx import numpy_helper

NATIVE_DIR = pathlib.Path(__file__).parent.parent / "native"


class UnsupportedGraph(Exception):
    """Raised when the input ONNX graph is outside this compiler's
    deliberately narrow supported class — a clean, explicit failure is the
    correct behavior here, not a best-effort guess."""


def parse_onnx(onnx_path):
    model = onnx.load(str(onnx_path))
    graph = model.graph
    initializers = {init.name: numpy_helper.to_array(init) for init in graph.initializer}

    ir = []
    for node in graph.node:
        if node.op_type == "Gemm":
            attrs = {a.name: onnx.helper.get_attribute_value(a) for a in node.attribute}
            if attrs.get("transB", 0) != 1 or attrs.get("alpha", 1.0) != 1.0 or attrs.get("beta", 1.0) != 1.0:
                raise UnsupportedGraph(f"Gemm with non-standard attrs (only transB=1, alpha=beta=1 supported): {attrs}")
            _, w_name, b_name = node.input
            W = initializers[w_name]
            out_dim, in_dim = W.shape
            ir.append({"op": "linear", "weight": w_name, "bias": b_name,
                       "in_dim": int(in_dim), "out_dim": int(out_dim)})
        elif node.op_type == "Relu":
            ir.append({"op": "relu"})
        elif node.op_type == "Softmax":
            axis = next((onnx.helper.get_attribute_value(a) for a in node.attribute if a.name == "axis"), -1)
            if axis not in (-1, 1):
                raise UnsupportedGraph(f"Softmax over unsupported axis: {axis} (only the last axis is supported)")
            ir.append({"op": "softmax"})
        else:
            raise UnsupportedGraph(
                f"op '{node.op_type}' is not supported by this minimal compiler "
                f"(supported: Gemm, Relu, Softmax)"
            )

    op_sequence = [op["op"] for op in ir]
    if op_sequence != ["linear", "relu", "linear", "softmax"]:
        raise UnsupportedGraph(
            f"this minimal compiler only supports Linear->ReLU->Linear->Softmax, got: {op_sequence}"
        )

    return ir, initializers


def generate_cpp(ir):
    """One line of C++ per IR op, calling common.hpp's shared functions —
    generated directly from the IR, not hand-written."""
    lin1, _relu, lin2, _softmax = ir

    return f"""\
// AUTO-GENERATED by python/sajal_compile.py — do not hand-edit.
// Generated from an ONNX graph: Gemm -> Relu -> Gemm -> Softmax.
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include "common.hpp"

struct CompiledModel {{
    static constexpr int IN_DIM = {lin1['in_dim']}, HIDDEN_DIM = {lin1['out_dim']}, OUT_DIM = {lin2['out_dim']};
    std::vector<float> fc1_weight, fc1_bias, fc2_weight, fc2_bias;

    std::vector<float> forward(const std::vector<float>& X, int n) const {{
        std::vector<float> buf0(static_cast<size_t>(n) * HIDDEN_DIM);
        linear(X.data(), n, IN_DIM, fc1_weight.data(), fc1_bias.data(), HIDDEN_DIM, buf0.data());
        relu_inplace(buf0.data(), buf0.size());
        std::vector<float> buf1(static_cast<size_t>(n) * OUT_DIM);
        linear(buf0.data(), n, HIDDEN_DIM, fc2_weight.data(), fc2_bias.data(), OUT_DIM, buf1.data());
        softmax_rows(buf1.data(), n, OUT_DIM);
        return buf1;
    }}
}};

CompiledModel load_model(const std::string& dir) {{
    CompiledModel m;
    m.fc1_weight = load_f32(dir + "/fc1_weight.bin", static_cast<size_t>(CompiledModel::HIDDEN_DIM) * CompiledModel::IN_DIM);
    m.fc1_bias = load_f32(dir + "/fc1_bias.bin", CompiledModel::HIDDEN_DIM);
    m.fc2_weight = load_f32(dir + "/fc2_weight.bin", static_cast<size_t>(CompiledModel::OUT_DIM) * CompiledModel::HIDDEN_DIM);
    m.fc2_bias = load_f32(dir + "/fc2_bias.bin", CompiledModel::OUT_DIM);
    return m;
}}

// Driver scaffolding: identical shape for every compiled model regardless of
// dims, so this part is fixed, not generated from the IR (mirrors mlp.cpp's
// own run/once modes exactly, for direct comparability).
void run_mode(const std::string& dir) {{
    CompiledModel m = load_model(dir);
    std::ifstream shapes(dir + "/shapes.txt");
    int in_dim, hidden_dim, out_dim, n_test;
    shapes >> in_dim >> hidden_dim >> out_dim >> n_test;
    auto X = load_f32(dir + "/test_inputs.bin", static_cast<size_t>(n_test) * in_dim);
    auto Y = m.forward(X, n_test);
    std::ofstream out(dir + "/native_outputs.bin", std::ios::binary);
    out.write(reinterpret_cast<char*>(Y.data()), Y.size() * sizeof(float));
    std::cerr << "wrote native_outputs.bin (" << n_test << "x" << out_dim << ")\\n";
}}

void once_mode(const std::string& dir) {{
    CompiledModel m = load_model(dir);
    std::vector<float> x(CompiledModel::IN_DIM, 0.1f);
    auto y = m.forward(x, 1);
    asm volatile("" : : "g"(y.data()) : "memory");
}}

int main(int argc, char** argv) {{
    if (argc != 3) {{ std::cerr << "usage: " << argv[0] << " <dir> <run|once>\\n"; return 1; }}
    std::string dir = argv[1], mode = argv[2];
    if (mode == "run") run_mode(dir);
    else if (mode == "once") once_mode(dir);
    else {{ std::cerr << "unknown mode\\n"; return 1; }}
    return 0;
}}
"""


def compile_model(onnx_path, source_artifacts_dir, out_dir):
    """onnx_path: the .onnx graph to compile.
    source_artifacts_dir: where test_inputs.bin/ref_outputs.bin already live
      (from the original hand-exported experiment) — copied through
      unchanged, so equivalence is checked against the SAME PyTorch
      reference every other experiment used, not freshly regenerated data.
    out_dir: where the compiled artifact (weights, shapes.txt, generated
      .cpp, compiled binary) is written — same file layout mlp_model.hpp
      already expects.
    """
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    source_artifacts_dir = pathlib.Path(source_artifacts_dir)

    ir, initializers = parse_onnx(onnx_path)
    lin1, _, lin2, _ = ir

    def save_f32(name, arr):
        arr.astype(np.float32).tofile(out_dir / name)

    save_f32("fc1_weight.bin", initializers[lin1["weight"]])
    save_f32("fc1_bias.bin", initializers[lin1["bias"]])
    save_f32("fc2_weight.bin", initializers[lin2["weight"]])
    save_f32("fc2_bias.bin", initializers[lin2["bias"]])

    n_test = int((source_artifacts_dir / "shapes.txt").read_text().split()[3])
    (out_dir / "shapes.txt").write_text(f"{lin1['in_dim']} {lin1['out_dim']} {lin2['out_dim']} {n_test}\n")

    shutil.copy(source_artifacts_dir / "test_inputs.bin", out_dir / "test_inputs.bin")
    shutil.copy(source_artifacts_dir / "ref_outputs.bin", out_dir / "ref_outputs.bin")

    (out_dir / "model.cpp").write_text(generate_cpp(ir))

    binary_path = out_dir / "model"
    result = subprocess.run(
        ["clang++", "-O3", "-std=c++17", "-Wall", "-Wextra", "-DACCELERATE_NEW_LAPACK",
         f"-I{NATIVE_DIR}", "-framework", "Accelerate", "-o", str(binary_path), str(out_dir / "model.cpp")],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"generated code failed to compile:\n{result.stdout}\n{result.stderr}")

    return out_dir, binary_path


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <model.onnx> <source_artifacts_dir> <out_dir>", file=sys.stderr)
        sys.exit(1)
    onnx_path, source_dir, out_dir_arg = sys.argv[1], sys.argv[2], sys.argv[3]
    try:
        out_dir, binary = compile_model(onnx_path, source_dir, out_dir_arg)
    except UnsupportedGraph as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
    print(f"compiled {onnx_path} -> {binary}")
